### ISSUE TITLE
Running on Linux mint (Ubuntu-based)?

### ISSUE THREAD

**Issue by Quicksoapy** [FunOrange/osu-trainer#22]
Has someone got it working on Linux Mint or Ubuntu? I used the following script to install the game. https://github.com/NelloKudo/osu-winello

**Comment by Inconn** [comment]
assuming you have a normal linux and osu-winello configuration, this script makes it kinda work
```sh
#!/usr/bin/env sh

export WINEESYNC=1
export WINEFSYNC=1
export PATH="$HOME/.local/share/osuconfig/wine-osu/bin:$PATH"
export WINEARCH=win64
export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-wineprefix/"
export WINEDLLOVERRIDES=winemenubuilder.exe=d#

wine osu-trainer.exe
```
but it doesn't really work since for some reason it generates the sped up audio but it doesn't generate the sped up map.

**Comment by Inconn** [comment]
nvm, it DOES work with that completely.
but for some reason the top diff of [this](https://osu.ppy.sh/beatmapsets/1268030#osu/2635238) map doesn't work for me:

**Comment by NoelleTGS** [comment]
@Inconn Getting an error using that script, too large to post the full thing but here's probably the important part
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'osu_trainer.Program' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Gdip
' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus.dll': Module not found. (Exception from HRESULT: 0x8007007E)
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip.Initialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipNewPrivateFontCollection(IntPtr& fontCollection)
   at System.Drawing.Text.PrivateFontCollection..ctor()
   at osu_trainer.Program..cctor() in C:\Users\funor\source\repos\osu-trainer\osu-trainer\Program.cs:line 12
   --- End of inner exception stack trace ---
   at osu_trainer.Program.Main() in C:\Users\funor\source\repos\osu-trainer\osu-trainer\Program.cs:line 19
wine: Unhandled exception 0xe0434352 in thread 1bc at address 0000000174013317 (thread 01bc), starting debugger...
```

**Comment by SneznyKocur** [comment]
for someone who needs this later, you need to install gdiplus from winetricks into the osu wineprefix
